name: workflow_dispatch
permissions:
  actions: read
  contents: read
  security-events: write
  statuses: write

on:
  push:
    branches: none # [ main ]
  pull_request:
    branches: none # [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  call-workflow-B:
    uses: VishwajitNagulkar/test-environment-sst/.github/workflows/sst_called.yml@master
    with:
      app-env: prod
      preview: create    ##create or destroy

env:
    ENV_VARS: >
        {

          "AWS_ACCOUNT_ID_FLOPROD": ${{ secrets.AWS_ACCOUNT_ID_FLOPROD }},
          "AWS_ACCOUNT_ID_FLOSTAG": ${{ secrets.AWS_ACCOUNT_ID_FLOSTAG }}
        }




